name: "CI Builds"
on: [push]
jobs:
  build-linux:
    strategy:
      matrix:
        dist:
          - i686
          - x86_64
    runs-on: ubuntu-latest
    container: veyon/ci.linux.${{matrix.dist}}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: .ci/windows/build.sh ${{matrix.dist}} $GITHUB_WORKSPACE /tmp
