build-windows:
  stage: build
  image: $CI_REGISTRY/veyon/ci-mingw-w64:5.0
  script:
    - .ci/windows/build.sh $ARCH
  parallel:
    matrix:
      - ARCH: [i686, x86_64]
  artifacts:
    paths: [ veyon-win* ]
    expire_in: 1 day
